### ISSUE TITLE
Additional validations 

### ISSUE THREAD

**Issue by jennaplusplus** [jennaplusplus/my-board-game-diary#9]
Write validations for models (mostly just checking that fields are present). Also have provisions that display errors in the view when validations do not pass.

**Comment by rmtolmach** [comment]
I'd like to work on this, Jenna. event.rb, game.rb, and player.rb all need validations (meetup.rb already has them written). And then were you thinking flash errors?

**Comment by jennaplusplus** [comment]
Sounds great! And either flash errors or a list of the errors messages would be fine. Your call. You can also use your own discretion for what validations you want/which fields should be mandatory/whatev.

**Comment by rmtolmach** [comment]
Sounds good!
